/* 
 * Content Delivery Management API
 *
 * <p>Cloud Content Delivery is a managed cloud service that hosts and delivers content to end users worldwide.</p> <p>You are currently viewing the documentation for the <b>Management API</b>, intended to be used by developers at build time for managing content. Refer to the <a href=\"https://content-api.cloud.unity3d.com/doc_client/\">Content Delivery Client API</a> for documentation about the API intended to be used at runtime by your game client.</p> <h2>Client SDK</h2> <p>The Content Delivery Management API is based on Swagger. The <a href=\"https://swagger.io/tools/swagger-codegen/\">Swagger Code Generator</a> can generate client libraries to integrate with your projects.</p> <p>A <a href=\"https://content-api.cloud.unity3d.com/doc/doc.json\">JSON schema</a> is required to generate a client for this API version.</p> <h2>Authentication</h2> <p>The Content Delivery Management API requires an API key associated with your Unity developer account. To access your API Key, please visit the <a href=\"https://developer.cloud.unity3d.com\">developer dashboard</a>.</p> <p>To authenticate requests, include a Basic Authentication header as a base64-encoded string 'username:password', using your API key as the password (and empty username).</p> <p>For example, an API key value of 'd6d2c026bac44b1ea7ac0332694a830e' would include an Authorization header like:</p> <p><b>Authorization: Basic OmQ2ZDJjMDI2YmFjNDRiMWVhN2FjMDMzMjY5NGE4MzBl</b></p> <h2>Pagination</h2> <p>Paged results take two parameters: the number of results to return per page (?per_page) and the page number based on that per page amount (?page). Page numbering starts with 1 and the default page size is 10.</p> <p>For instance, if there are 40 results and you specify page=2&per_page=10, you will receive records 11-20. Paged results will also return a Content-Range header. In the example above the content range header will look like this:</p> <p><b>Content-Range: items 11-20/40</b></p>
 *
 * OpenAPI spec version: 0.9.112
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using CloudContentDeliveryManagment.Client;
using CloudContentDeliveryManagment.Model;

namespace CloudContentDeliveryManagment.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContentApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create content upload for TUS
        /// </summary>
        /// <remarks>
        /// Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns></returns>
        void CreateContent (string bucketid, string entryid);

        /// <summary>
        /// Create content upload for TUS
        /// </summary>
        /// <remarks>
        /// Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateContentWithHttpInfo (string bucketid, string entryid);
        /// <summary>
        /// Get content by entryid
        /// </summary>
        /// <remarks>
        /// Gets the content for a given entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetContent (string bucketid, string entryid, string versionid = null);

        /// <summary>
        /// Get content by entryid
        /// </summary>
        /// <remarks>
        /// Gets the content for a given entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetContentWithHttpInfo (string bucketid, string entryid, string versionid = null);
        /// <summary>
        /// Get content status by entryid
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns></returns>
        void GetContentStatus (string bucketid, string entryid, string versionid = null);

        /// <summary>
        /// Get content status by entryid
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GetContentStatusWithHttpInfo (string bucketid, string entryid, string versionid = null);
        /// <summary>
        /// Get content status for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns></returns>
        void GetContentStatusVersion (string bucketid, string entryid, string versionid);

        /// <summary>
        /// Get content status for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GetContentStatusVersionWithHttpInfo (string bucketid, string entryid, string versionid);
        /// <summary>
        /// Get content for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetContentVersion (string bucketid, string entryid, string versionid);

        /// <summary>
        /// Get content for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetContentVersionWithHttpInfo (string bucketid, string entryid, string versionid);
        /// <summary>
        /// Upload content for entry
        /// </summary>
        /// <remarks>
        /// Uploads or resumes uploading content for an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns></returns>
        void UploadContent (string bucketid, string entryid, System.IO.Stream _file);

        /// <summary>
        /// Upload content for entry
        /// </summary>
        /// <remarks>
        /// Uploads or resumes uploading content for an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UploadContentWithHttpInfo (string bucketid, string entryid, System.IO.Stream _file);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create content upload for TUS
        /// </summary>
        /// <remarks>
        /// Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateContentAsync (string bucketid, string entryid);

        /// <summary>
        /// Create content upload for TUS
        /// </summary>
        /// <remarks>
        /// Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateContentAsyncWithHttpInfo (string bucketid, string entryid);
        /// <summary>
        /// Get content by entryid
        /// </summary>
        /// <remarks>
        /// Gets the content for a given entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetContentAsync (string bucketid, string entryid, string versionid = null);

        /// <summary>
        /// Get content by entryid
        /// </summary>
        /// <remarks>
        /// Gets the content for a given entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetContentAsyncWithHttpInfo (string bucketid, string entryid, string versionid = null);
        /// <summary>
        /// Get content status by entryid
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GetContentStatusAsync (string bucketid, string entryid, string versionid = null);

        /// <summary>
        /// Get content status by entryid
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetContentStatusAsyncWithHttpInfo (string bucketid, string entryid, string versionid = null);
        /// <summary>
        /// Get content status for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GetContentStatusVersionAsync (string bucketid, string entryid, string versionid);

        /// <summary>
        /// Get content status for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the status of uploaded content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetContentStatusVersionAsyncWithHttpInfo (string bucketid, string entryid, string versionid);
        /// <summary>
        /// Get content for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetContentVersionAsync (string bucketid, string entryid, string versionid);

        /// <summary>
        /// Get content for version of entry
        /// </summary>
        /// <remarks>
        /// Gets the content for a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetContentVersionAsyncWithHttpInfo (string bucketid, string entryid, string versionid);
        /// <summary>
        /// Upload content for entry
        /// </summary>
        /// <remarks>
        /// Uploads or resumes uploading content for an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UploadContentAsync (string bucketid, string entryid, System.IO.Stream _file);

        /// <summary>
        /// Upload content for entry
        /// </summary>
        /// <remarks>
        /// Uploads or resumes uploading content for an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UploadContentAsyncWithHttpInfo (string bucketid, string entryid, System.IO.Stream _file);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ContentApi : IContentApi
    {
        private CloudContentDeliveryManagment.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ContentApi(String basePath)
        {
            this.Configuration = new CloudContentDeliveryManagment.Client.Configuration { BasePath = basePath };

            ExceptionFactory = CloudContentDeliveryManagment.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ContentApi(CloudContentDeliveryManagment.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = CloudContentDeliveryManagment.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = CloudContentDeliveryManagment.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CloudContentDeliveryManagment.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CloudContentDeliveryManagment.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create content upload for TUS Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns></returns>
        public void CreateContent (string bucketid, string entryid)
        {
             CreateContentWithHttpInfo(bucketid, entryid);
        }

        /// <summary>
        /// Create content upload for TUS Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> CreateContentWithHttpInfo (string bucketid, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->CreateContent");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->CreateContent");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Create content upload for TUS Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateContentAsync (string bucketid, string entryid)
        {
             await CreateContentAsyncWithHttpInfo(bucketid, entryid);

        }

        /// <summary>
        /// Create content upload for TUS Simply returns the content upload URL in the Location header for &lt;a href&#x3D;\&quot;https://tus.io/\&quot; rel&#x3D;\&quot;noopener noreferrer\&quot; target&#x3D;\&quot;_blank\&quot;&gt;TUS&lt;/a&gt; implementations. This endpoint is not required for most file uploads.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> CreateContentAsyncWithHttpInfo (string bucketid, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->CreateContent");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->CreateContent");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get content by entryid Gets the content for a given entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetContent (string bucketid, string entryid, string versionid = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetContentWithHttpInfo(bucketid, entryid, versionid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get content by entryid Gets the content for a given entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetContentWithHttpInfo (string bucketid, string entryid, string versionid = null)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContent");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContent");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "versionid", versionid)); // query parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Get content by entryid Gets the content for a given entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetContentAsync (string bucketid, string entryid, string versionid = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetContentAsyncWithHttpInfo(bucketid, entryid, versionid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get content by entryid Gets the content for a given entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetContentAsyncWithHttpInfo (string bucketid, string entryid, string versionid = null)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContent");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContent");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "versionid", versionid)); // query parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Get content status by entryid Gets the status of uploaded content.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns></returns>
        public void GetContentStatus (string bucketid, string entryid, string versionid = null)
        {
             GetContentStatusWithHttpInfo(bucketid, entryid, versionid);
        }

        /// <summary>
        /// Get content status by entryid Gets the status of uploaded content.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> GetContentStatusWithHttpInfo (string bucketid, string entryid, string versionid = null)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContentStatus");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContentStatus");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "versionid", versionid)); // query parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContentStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get content status by entryid Gets the status of uploaded content.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GetContentStatusAsync (string bucketid, string entryid, string versionid = null)
        {
             await GetContentStatusAsyncWithHttpInfo(bucketid, entryid, versionid);

        }

        /// <summary>
        /// Get content status by entryid Gets the status of uploaded content.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GetContentStatusAsyncWithHttpInfo (string bucketid, string entryid, string versionid = null)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContentStatus");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContentStatus");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "versionid", versionid)); // query parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContentStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get content status for version of entry Gets the status of uploaded content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns></returns>
        public void GetContentStatusVersion (string bucketid, string entryid, string versionid)
        {
             GetContentStatusVersionWithHttpInfo(bucketid, entryid, versionid);
        }

        /// <summary>
        /// Get content status for version of entry Gets the status of uploaded content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> GetContentStatusVersionWithHttpInfo (string bucketid, string entryid, string versionid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContentStatusVersion");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContentStatusVersion");
            // verify the required parameter 'versionid' is set
            if (versionid == null)
                throw new ApiException(400, "Missing required parameter 'versionid' when calling ContentApi->GetContentStatusVersion");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/versions/{versionid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarPathParams.Add("versionid", this.Configuration.ApiClient.ParameterToString(versionid)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContentStatusVersion", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get content status for version of entry Gets the status of uploaded content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GetContentStatusVersionAsync (string bucketid, string entryid, string versionid)
        {
             await GetContentStatusVersionAsyncWithHttpInfo(bucketid, entryid, versionid);

        }

        /// <summary>
        /// Get content status for version of entry Gets the status of uploaded content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GetContentStatusVersionAsyncWithHttpInfo (string bucketid, string entryid, string versionid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContentStatusVersion");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContentStatusVersion");
            // verify the required parameter 'versionid' is set
            if (versionid == null)
                throw new ApiException(400, "Missing required parameter 'versionid' when calling ContentApi->GetContentStatusVersion");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/versions/{versionid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarPathParams.Add("versionid", this.Configuration.ApiClient.ParameterToString(versionid)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContentStatusVersion", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get content for version of entry Gets the content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetContentVersion (string bucketid, string entryid, string versionid)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetContentVersionWithHttpInfo(bucketid, entryid, versionid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get content for version of entry Gets the content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetContentVersionWithHttpInfo (string bucketid, string entryid, string versionid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContentVersion");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContentVersion");
            // verify the required parameter 'versionid' is set
            if (versionid == null)
                throw new ApiException(400, "Missing required parameter 'versionid' when calling ContentApi->GetContentVersion");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/versions/{versionid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarPathParams.Add("versionid", this.Configuration.ApiClient.ParameterToString(versionid)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContentVersion", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Get content for version of entry Gets the content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetContentVersionAsync (string bucketid, string entryid, string versionid)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetContentVersionAsyncWithHttpInfo(bucketid, entryid, versionid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get content for version of entry Gets the content for a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetContentVersionAsyncWithHttpInfo (string bucketid, string entryid, string versionid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->GetContentVersion");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->GetContentVersion");
            // verify the required parameter 'versionid' is set
            if (versionid == null)
                throw new ApiException(400, "Missing required parameter 'versionid' when calling ContentApi->GetContentVersion");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/versions/{versionid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarPathParams.Add("versionid", this.Configuration.ApiClient.ParameterToString(versionid)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContentVersion", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Upload content for entry Uploads or resumes uploading content for an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns></returns>
        public void UploadContent (string bucketid, string entryid, System.IO.Stream _file)
        {
             UploadContentWithHttpInfo(bucketid, entryid, _file);
        }

        /// <summary>
        /// Upload content for entry Uploads or resumes uploading content for an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> UploadContentWithHttpInfo (string bucketid, string entryid, System.IO.Stream _file)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->UploadContent");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->UploadContent");
            // verify the required parameter '_file' is set
            if (_file == null)
                throw new ApiException(400, "Missing required parameter '_file' when calling ContentApi->UploadContent");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (_file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", _file));

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UploadContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Upload content for entry Uploads or resumes uploading content for an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UploadContentAsync (string bucketid, string entryid, System.IO.Stream _file)
        {
             await UploadContentAsyncWithHttpInfo(bucketid, entryid, _file);

        }

        /// <summary>
        /// Upload content for entry Uploads or resumes uploading content for an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="_file">File content</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> UploadContentAsyncWithHttpInfo (string bucketid, string entryid, System.IO.Stream _file)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling ContentApi->UploadContent");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling ContentApi->UploadContent");
            // verify the required parameter '_file' is set
            if (_file == null)
                throw new ApiException(400, "Missing required parameter '_file' when calling ContentApi->UploadContent");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/content/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (_file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", _file));

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UploadContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
