/* 
 * Content Delivery Management API
 *
 * <p>Cloud Content Delivery is a managed cloud service that hosts and delivers content to end users worldwide.</p> <p>You are currently viewing the documentation for the <b>Management API</b>, intended to be used by developers at build time for managing content. Refer to the <a href=\"https://content-api.cloud.unity3d.com/doc_client/\">Content Delivery Client API</a> for documentation about the API intended to be used at runtime by your game client.</p> <h2>Client SDK</h2> <p>The Content Delivery Management API is based on Swagger. The <a href=\"https://swagger.io/tools/swagger-codegen/\">Swagger Code Generator</a> can generate client libraries to integrate with your projects.</p> <p>A <a href=\"https://content-api.cloud.unity3d.com/doc/doc.json\">JSON schema</a> is required to generate a client for this API version.</p> <h2>Authentication</h2> <p>The Content Delivery Management API requires an API key associated with your Unity developer account. To access your API Key, please visit the <a href=\"https://developer.cloud.unity3d.com\">developer dashboard</a>.</p> <p>To authenticate requests, include a Basic Authentication header as a base64-encoded string 'username:password', using your API key as the password (and empty username).</p> <p>For example, an API key value of 'd6d2c026bac44b1ea7ac0332694a830e' would include an Authorization header like:</p> <p><b>Authorization: Basic OmQ2ZDJjMDI2YmFjNDRiMWVhN2FjMDMzMjY5NGE4MzBl</b></p> <h2>Pagination</h2> <p>Paged results take two parameters: the number of results to return per page (?per_page) and the page number based on that per page amount (?page). Page numbering starts with 1 and the default page size is 10.</p> <p>For instance, if there are 40 results and you specify page=2&per_page=10, you will receive records 11-20. Paged results will also return a Content-Range header. In the example above the content range header will look like this:</p> <p><b>Content-Range: items 11-20/40</b></p>
 *
 * OpenAPI spec version: 0.9.112
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CloudContentDeliveryManagment.Client.SwaggerDateConverter;

namespace CloudContentDeliveryManagment.Model
{
    /// <summary>
    /// ReleaseentryCreate
    /// </summary>
    [DataContract, Serializable]
    public partial class ReleaseentryCreate :  IEquatable<ReleaseentryCreate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseentryCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReleaseentryCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseentryCreate" /> class.
        /// </summary>
        /// <param name="entryid">entryid (required).</param>
        /// <param name="versionid">versionid (required).</param>
        public ReleaseentryCreate(Guid? entryid = default(Guid?), Guid? versionid = default(Guid?))
        {
            // to ensure "entryid" is required (not null)
            if (entryid == null)
            {
                throw new InvalidDataException("entryid is a required property for ReleaseentryCreate and cannot be null");
            }
            else
            {
                this.Entryid = entryid;
            }
            // to ensure "versionid" is required (not null)
            if (versionid == null)
            {
                throw new InvalidDataException("versionid is a required property for ReleaseentryCreate and cannot be null");
            }
            else
            {
                this.Versionid = versionid;
            }
        }
        
        /// <summary>
        /// Gets or Sets Entryid
        /// </summary>
        [DataMember(Name="entryid", EmitDefaultValue=false)]
        public Guid? Entryid { get; set; }

        /// <summary>
        /// Gets or Sets Versionid
        /// </summary>
        [DataMember(Name="versionid", EmitDefaultValue=false)]
        public Guid? Versionid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReleaseentryCreate {\n");
            sb.Append("  Entryid: ").Append(Entryid).Append("\n");
            sb.Append("  Versionid: ").Append(Versionid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReleaseentryCreate);
        }

        /// <summary>
        /// Returns true if ReleaseentryCreate instances are equal
        /// </summary>
        /// <param name="input">Instance of ReleaseentryCreate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReleaseentryCreate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Entryid == input.Entryid ||
                    (this.Entryid != null &&
                    this.Entryid.Equals(input.Entryid))
                ) && 
                (
                    this.Versionid == input.Versionid ||
                    (this.Versionid != null &&
                    this.Versionid.Equals(input.Versionid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Entryid != null)
                    hashCode = hashCode * 59 + this.Entryid.GetHashCode();
                if (this.Versionid != null)
                    hashCode = hashCode * 59 + this.Versionid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
