/* 
 * Content Delivery Client API
 *
 * <p>Cloud Content Delivery is a managed cloud service that hosts and delivers content to end users worldwide.</p> <p>You are currently viewing the documentation for the <b>Client API</b>, which is intended to be used at runtime by your game client. The <a href=\"https://content-api.cloud.unity3d.com/doc/\">Content Delivery Management API</a> is intended to be used by developers at build time for managing content.</p> <h2>Client API Domain</h2> <p>The Client API base domain uses a different domain from the Management API and is in the format:</p> <pre>https://9a474388-ba4d-469a-bf3c-8b557f89012d.client-api.unity3dusercontent.com/</pre> <h2>Client SDK</h2> <p>The Content Delivery Client API is based on Swagger. You can use the <a href=\"https://swagger.io/tools/swagger-codegen/\">Swagger Code Generator</a> and a client schema document to integrate client libraries with your projects.</p> <p>Once you create a bucket with the Management API, the Client API is accessible via a per-project API domain. To download the schema document necessary to generate a client library, put in your Project ID and click Download.</p> <form action=\"https://content-api.cloud.unity3d.com/doc_client/doc.json\" method=\"GET\"> <div><label for=\"projectID\">Project ID</label><input type=\"text\" name=\"projectID\" id=\"projectID\" required /></div> <div><button type=\"submit\">Download</button></div> </form> <h2>Authentication</h2> <p>Everything in the Client API requires NO AUTHENTICATION. The data served from this API is effectively public.</p>
 *
 * OpenAPI spec version: 0.9.112
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CloudContentDeliveryClient.Client.SwaggerDateConverter;

namespace CloudContentDeliveryClient.Model
{
    /// <summary>
    /// Entry
    /// </summary>
    [DataContract]
    public partial class Entry :  IEquatable<Entry>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Entry" /> class.
        /// </summary>
        /// <param name="contentHash">contentHash.</param>
        /// <param name="contentLink">contentLink.</param>
        /// <param name="contentSize">contentSize.</param>
        /// <param name="contentType">contentType.</param>
        /// <param name="currentVersionid">currentVersionid.</param>
        /// <param name="entryid">entryid.</param>
        /// <param name="labels">labels.</param>
        /// <param name="lastModified">lastModified.</param>
        /// <param name="link">link.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="path">path.</param>
        public Entry(string contentHash = default(string), string contentLink = default(string), int? contentSize = default(int?), string contentType = default(string), Guid? currentVersionid = default(Guid?), Guid? entryid = default(Guid?), List<string> labels = default(List<string>), DateTime? lastModified = default(DateTime?), string link = default(string), Object metadata = default(Object), string path = default(string))
        {
            this.ContentHash = contentHash;
            this.ContentLink = contentLink;
            this.ContentSize = contentSize;
            this.ContentType = contentType;
            this.CurrentVersionid = currentVersionid;
            this.Entryid = entryid;
            this.Labels = labels;
            this.LastModified = lastModified;
            this.Link = link;
            this.Metadata = metadata;
            this.Path = path;
        }
        
        /// <summary>
        /// Gets or Sets ContentHash
        /// </summary>
        [DataMember(Name="content_hash", EmitDefaultValue=false)]
        public string ContentHash { get; set; }

        /// <summary>
        /// Gets or Sets ContentLink
        /// </summary>
        [DataMember(Name="content_link", EmitDefaultValue=false)]
        public string ContentLink { get; set; }

        /// <summary>
        /// Gets or Sets ContentSize
        /// </summary>
        [DataMember(Name="content_size", EmitDefaultValue=false)]
        public int? ContentSize { get; set; }

        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [DataMember(Name="content_type", EmitDefaultValue=false)]
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or Sets CurrentVersionid
        /// </summary>
        [DataMember(Name="current_versionid", EmitDefaultValue=false)]
        public Guid? CurrentVersionid { get; set; }

        /// <summary>
        /// Gets or Sets Entryid
        /// </summary>
        [DataMember(Name="entryid", EmitDefaultValue=false)]
        public Guid? Entryid { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [DataMember(Name="labels", EmitDefaultValue=false)]
        public List<string> Labels { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name="last_modified", EmitDefaultValue=false)]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name="link", EmitDefaultValue=false)]
        public string Link { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name="metadata", EmitDefaultValue=false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name="path", EmitDefaultValue=false)]
        public string Path { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Entry {\n");
            sb.Append("  ContentHash: ").Append(ContentHash).Append("\n");
            sb.Append("  ContentLink: ").Append(ContentLink).Append("\n");
            sb.Append("  ContentSize: ").Append(ContentSize).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  CurrentVersionid: ").Append(CurrentVersionid).Append("\n");
            sb.Append("  Entryid: ").Append(Entryid).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Entry);
        }

        /// <summary>
        /// Returns true if Entry instances are equal
        /// </summary>
        /// <param name="input">Instance of Entry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Entry input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ContentHash == input.ContentHash ||
                    (this.ContentHash != null &&
                    this.ContentHash.Equals(input.ContentHash))
                ) && 
                (
                    this.ContentLink == input.ContentLink ||
                    (this.ContentLink != null &&
                    this.ContentLink.Equals(input.ContentLink))
                ) && 
                (
                    this.ContentSize == input.ContentSize ||
                    (this.ContentSize != null &&
                    this.ContentSize.Equals(input.ContentSize))
                ) && 
                (
                    this.ContentType == input.ContentType ||
                    (this.ContentType != null &&
                    this.ContentType.Equals(input.ContentType))
                ) && 
                (
                    this.CurrentVersionid == input.CurrentVersionid ||
                    (this.CurrentVersionid != null &&
                    this.CurrentVersionid.Equals(input.CurrentVersionid))
                ) && 
                (
                    this.Entryid == input.Entryid ||
                    (this.Entryid != null &&
                    this.Entryid.Equals(input.Entryid))
                ) && 
                (
                    this.Labels == input.Labels ||
                    this.Labels != null &&
                    this.Labels.SequenceEqual(input.Labels)
                ) && 
                (
                    this.LastModified == input.LastModified ||
                    (this.LastModified != null &&
                    this.LastModified.Equals(input.LastModified))
                ) && 
                (
                    this.Link == input.Link ||
                    (this.Link != null &&
                    this.Link.Equals(input.Link))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                ) && 
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContentHash != null)
                    hashCode = hashCode * 59 + this.ContentHash.GetHashCode();
                if (this.ContentLink != null)
                    hashCode = hashCode * 59 + this.ContentLink.GetHashCode();
                if (this.ContentSize != null)
                    hashCode = hashCode * 59 + this.ContentSize.GetHashCode();
                if (this.ContentType != null)
                    hashCode = hashCode * 59 + this.ContentType.GetHashCode();
                if (this.CurrentVersionid != null)
                    hashCode = hashCode * 59 + this.CurrentVersionid.GetHashCode();
                if (this.Entryid != null)
                    hashCode = hashCode * 59 + this.Entryid.GetHashCode();
                if (this.Labels != null)
                    hashCode = hashCode * 59 + this.Labels.GetHashCode();
                if (this.LastModified != null)
                    hashCode = hashCode * 59 + this.LastModified.GetHashCode();
                if (this.Link != null)
                    hashCode = hashCode * 59 + this.Link.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ContentHash (string) pattern
            Regex regexContentHash = new Regex(@"^[a-fA-F0-9]+$", RegexOptions.CultureInvariant);
            if (false == regexContentHash.Match(this.ContentHash).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ContentHash, must match a pattern of " + regexContentHash, new [] { "ContentHash" });
            }

            // ContentSize (int?) minimum
            if(this.ContentSize < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ContentSize, must be a value greater than or equal to 0.", new [] { "ContentSize" });
            }

            // Path (string) pattern
            Regex regexPath = new Regex(@"^\\S.*$", RegexOptions.CultureInvariant);
            if (false == regexPath.Match(this.Path).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Path, must match a pattern of " + regexPath, new [] { "Path" });
            }

            yield break;
        }
    }

}
