/* 
 * Content Delivery Client API
 *
 * <p>Cloud Content Delivery is a managed cloud service that hosts and delivers content to end users worldwide.</p> <p>You are currently viewing the documentation for the <b>Client API</b>, which is intended to be used at runtime by your game client. The <a href=\"https://content-api.cloud.unity3d.com/doc/\">Content Delivery Management API</a> is intended to be used by developers at build time for managing content.</p> <h2>Client API Domain</h2> <p>The Client API base domain uses a different domain from the Management API and is in the format:</p> <pre>https://9a474388-ba4d-469a-bf3c-8b557f89012d.client-api.unity3dusercontent.com/</pre> <h2>Client SDK</h2> <p>The Content Delivery Client API is based on Swagger. You can use the <a href=\"https://swagger.io/tools/swagger-codegen/\">Swagger Code Generator</a> and a client schema document to integrate client libraries with your projects.</p> <p>Once you create a bucket with the Management API, the Client API is accessible via a per-project API domain. To download the schema document necessary to generate a client library, put in your Project ID and click Download.</p> <form action=\"https://content-api.cloud.unity3d.com/doc_client/doc.json\" method=\"GET\"> <div><label for=\"projectID\">Project ID</label><input type=\"text\" name=\"projectID\" id=\"projectID\" required /></div> <div><button type=\"submit\">Download</button></div> </form> <h2>Authentication</h2> <p>Everything in the Client API requires NO AUTHENTICATION. The data served from this API is effectively public.</p>
 *
 * OpenAPI spec version: 0.9.112
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CloudContentDeliveryClient.Client.SwaggerDateConverter;

namespace CloudContentDeliveryClient.Model
{
    /// <summary>
    /// Nocontent
    /// </summary>
    [DataContract]
    public partial class Nocontent :  IEquatable<Nocontent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Nocontent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public Nocontent()
        {
        }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Nocontent {\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Nocontent);
        }

        /// <summary>
        /// Returns true if Nocontent instances are equal
        /// </summary>
        /// <param name="input">Instance of Nocontent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Nocontent input)
        {
            if (input == null)
                return false;

            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
