/* 
 * Content Delivery Client API
 *
 * <p>Cloud Content Delivery is a managed cloud service that hosts and delivers content to end users worldwide.</p> <p>You are currently viewing the documentation for the <b>Client API</b>, which is intended to be used at runtime by your game client. The <a href=\"https://content-api.cloud.unity3d.com/doc/\">Content Delivery Management API</a> is intended to be used by developers at build time for managing content.</p> <h2>Client API Domain</h2> <p>The Client API base domain uses a different domain from the Management API and is in the format:</p> <pre>https://9a474388-ba4d-469a-bf3c-8b557f89012d.client-api.unity3dusercontent.com/</pre> <h2>Client SDK</h2> <p>The Content Delivery Client API is based on Swagger. You can use the <a href=\"https://swagger.io/tools/swagger-codegen/\">Swagger Code Generator</a> and a client schema document to integrate client libraries with your projects.</p> <p>Once you create a bucket with the Management API, the Client API is accessible via a per-project API domain. To download the schema document necessary to generate a client library, put in your Project ID and click Download.</p> <form action=\"https://content-api.cloud.unity3d.com/doc_client/doc.json\" method=\"GET\"> <div><label for=\"projectID\">Project ID</label><input type=\"text\" name=\"projectID\" id=\"projectID\" required /></div> <div><button type=\"submit\">Download</button></div> </form> <h2>Authentication</h2> <p>Everything in the Client API requires NO AUTHENTICATION. The data served from this API is effectively public.</p>
 *
 * OpenAPI spec version: 0.9.112
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using CloudContentDeliveryClient.Client;
using CloudContentDeliveryClient.Model;

namespace CloudContentDeliveryClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEntriesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get entry by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry by path for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Entry</returns>
        Entry GetEntryByPathPublic (string bucketid, string path, string versionid = null);

        /// <summary>
        /// Get entry by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry by path for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>ApiResponse of Entry</returns>
        ApiResponse<Entry> GetEntryByPathPublicWithHttpInfo (string bucketid, string path, string versionid = null);
        /// <summary>
        /// Get entry in a badged release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>Entry</returns>
        Entry GetEntryForBadgeByPathPublic (string bucketid, string badgename, string path);

        /// <summary>
        /// Get entry in a badged release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>ApiResponse of Entry</returns>
        ApiResponse<Entry> GetEntryForBadgeByPathPublicWithHttpInfo (string bucketid, string badgename, string path);
        /// <summary>
        /// Get entry in a badged release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Entry</returns>
        Entry GetEntryForBadgePublic (string bucketid, string badgename, string entryid);

        /// <summary>
        /// Get entry in a badged release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Entry</returns>
        ApiResponse<Entry> GetEntryForBadgePublicWithHttpInfo (string bucketid, string badgename, string entryid);
        /// <summary>
        /// Get entry in release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>Entry</returns>
        Entry GetEntryForReleaseByPathPublic (string bucketid, string releaseid, string path);

        /// <summary>
        /// Get entry in release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>ApiResponse of Entry</returns>
        ApiResponse<Entry> GetEntryForReleaseByPathPublicWithHttpInfo (string bucketid, string releaseid, string path);
        /// <summary>
        /// Get entry in release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Entry</returns>
        Entry GetEntryForReleasePublic (string bucketid, string releaseid, string entryid);

        /// <summary>
        /// Get entry in release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Entry</returns>
        ApiResponse<Entry> GetEntryForReleasePublicWithHttpInfo (string bucketid, string releaseid, string entryid);
        /// <summary>
        /// Get entry by id
        /// </summary>
        /// <remarks>
        /// Gets a single entry by id for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Entry</returns>
        Entry GetEntryPublic (string bucketid, string entryid);

        /// <summary>
        /// Get entry by id
        /// </summary>
        /// <remarks>
        /// Gets a single entry by id for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Entry</returns>
        ApiResponse<Entry> GetEntryPublicWithHttpInfo (string bucketid, string entryid);
        /// <summary>
        /// Get entry version
        /// </summary>
        /// <remarks>
        /// Gets a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Entry</returns>
        Entry GetEntryVersionPublic (string bucketid, string entryid, string versionid);

        /// <summary>
        /// Get entry version
        /// </summary>
        /// <remarks>
        /// Gets a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>ApiResponse of Entry</returns>
        ApiResponse<Entry> GetEntryVersionPublicWithHttpInfo (string bucketid, string entryid, string versionid);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get entry by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry by path for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of Entry</returns>
        System.Threading.Tasks.Task<Entry> GetEntryByPathPublicAsync (string bucketid, string path, string versionid = null);

        /// <summary>
        /// Get entry by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry by path for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryByPathPublicAsyncWithHttpInfo (string bucketid, string path, string versionid = null);
        /// <summary>
        /// Get entry in a badged release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>Task of Entry</returns>
        System.Threading.Tasks.Task<Entry> GetEntryForBadgeByPathPublicAsync (string bucketid, string badgename, string path);

        /// <summary>
        /// Get entry in a badged release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForBadgeByPathPublicAsyncWithHttpInfo (string bucketid, string badgename, string path);
        /// <summary>
        /// Get entry in a badged release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of Entry</returns>
        System.Threading.Tasks.Task<Entry> GetEntryForBadgePublicAsync (string bucketid, string badgename, string entryid);

        /// <summary>
        /// Get entry in a badged release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given badged release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForBadgePublicAsyncWithHttpInfo (string bucketid, string badgename, string entryid);
        /// <summary>
        /// Get entry in release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>Task of Entry</returns>
        System.Threading.Tasks.Task<Entry> GetEntryForReleaseByPathPublicAsync (string bucketid, string releaseid, string path);

        /// <summary>
        /// Get entry in release by path
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release by path.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForReleaseByPathPublicAsyncWithHttpInfo (string bucketid, string releaseid, string path);
        /// <summary>
        /// Get entry in release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of Entry</returns>
        System.Threading.Tasks.Task<Entry> GetEntryForReleasePublicAsync (string bucketid, string releaseid, string entryid);

        /// <summary>
        /// Get entry in release
        /// </summary>
        /// <remarks>
        /// Gets a single entry for a given release.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForReleasePublicAsyncWithHttpInfo (string bucketid, string releaseid, string entryid);
        /// <summary>
        /// Get entry by id
        /// </summary>
        /// <remarks>
        /// Gets a single entry by id for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of Entry</returns>
        System.Threading.Tasks.Task<Entry> GetEntryPublicAsync (string bucketid, string entryid);

        /// <summary>
        /// Get entry by id
        /// </summary>
        /// <remarks>
        /// Gets a single entry by id for a given bucket.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryPublicAsyncWithHttpInfo (string bucketid, string entryid);
        /// <summary>
        /// Get entry version
        /// </summary>
        /// <remarks>
        /// Gets a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of Entry</returns>
        System.Threading.Tasks.Task<Entry> GetEntryVersionPublicAsync (string bucketid, string entryid, string versionid);

        /// <summary>
        /// Get entry version
        /// </summary>
        /// <remarks>
        /// Gets a specific version of an entry.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryVersionPublicAsyncWithHttpInfo (string bucketid, string entryid, string versionid);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EntriesApi : IEntriesApi
    {
        private CloudContentDeliveryClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EntriesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EntriesApi(String basePath)
        {
            this.Configuration = new CloudContentDeliveryClient.Client.Configuration { BasePath = basePath };

            ExceptionFactory = CloudContentDeliveryClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EntriesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EntriesApi(CloudContentDeliveryClient.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = CloudContentDeliveryClient.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = CloudContentDeliveryClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CloudContentDeliveryClient.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CloudContentDeliveryClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get entry by path Gets a single entry by path for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Entry</returns>
        public Entry GetEntryByPathPublic (string bucketid, string path, string versionid = null)
        {
             ApiResponse<Entry> localVarResponse = GetEntryByPathPublicWithHttpInfo(bucketid, path, versionid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get entry by path Gets a single entry by path for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>ApiResponse of Entry</returns>
        public ApiResponse< Entry > GetEntryByPathPublicWithHttpInfo (string bucketid, string path, string versionid = null)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryByPathPublic");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling EntriesApi->GetEntryByPathPublic");

            var localVarPath = "/buckets/{bucketid}/entry_by_path/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (path != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "path", path)); // query parameter
            if (versionid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "versionid", versionid)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryByPathPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry by path Gets a single entry by path for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of Entry</returns>
        public async System.Threading.Tasks.Task<Entry> GetEntryByPathPublicAsync (string bucketid, string path, string versionid = null)
        {
             ApiResponse<Entry> localVarResponse = await GetEntryByPathPublicAsyncWithHttpInfo(bucketid, path, versionid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get entry by path Gets a single entry by path for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="path">Path</param>
        /// <param name="versionid">Version ID (optional)</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryByPathPublicAsyncWithHttpInfo (string bucketid, string path, string versionid = null)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryByPathPublic");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling EntriesApi->GetEntryByPathPublic");

            var localVarPath = "/buckets/{bucketid}/entry_by_path/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (path != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "path", path)); // query parameter
            if (versionid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "versionid", versionid)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryByPathPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in a badged release by path Gets a single entry for a given badged release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>Entry</returns>
        public Entry GetEntryForBadgeByPathPublic (string bucketid, string badgename, string path)
        {
             ApiResponse<Entry> localVarResponse = GetEntryForBadgeByPathPublicWithHttpInfo(bucketid, badgename, path);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get entry in a badged release by path Gets a single entry for a given badged release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>ApiResponse of Entry</returns>
        public ApiResponse< Entry > GetEntryForBadgeByPathPublicWithHttpInfo (string bucketid, string badgename, string path)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForBadgeByPathPublic");
            // verify the required parameter 'badgename' is set
            if (badgename == null)
                throw new ApiException(400, "Missing required parameter 'badgename' when calling EntriesApi->GetEntryForBadgeByPathPublic");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling EntriesApi->GetEntryForBadgeByPathPublic");

            var localVarPath = "/buckets/{bucketid}/release_by_badge/{badgename}/entry_by_path/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (badgename != null) localVarPathParams.Add("badgename", this.Configuration.ApiClient.ParameterToString(badgename)); // path parameter
            if (path != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "path", path)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForBadgeByPathPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in a badged release by path Gets a single entry for a given badged release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>Task of Entry</returns>
        public async System.Threading.Tasks.Task<Entry> GetEntryForBadgeByPathPublicAsync (string bucketid, string badgename, string path)
        {
             ApiResponse<Entry> localVarResponse = await GetEntryForBadgeByPathPublicAsyncWithHttpInfo(bucketid, badgename, path);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get entry in a badged release by path Gets a single entry for a given badged release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="path">Path</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForBadgeByPathPublicAsyncWithHttpInfo (string bucketid, string badgename, string path)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForBadgeByPathPublic");
            // verify the required parameter 'badgename' is set
            if (badgename == null)
                throw new ApiException(400, "Missing required parameter 'badgename' when calling EntriesApi->GetEntryForBadgeByPathPublic");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling EntriesApi->GetEntryForBadgeByPathPublic");

            var localVarPath = "/buckets/{bucketid}/release_by_badge/{badgename}/entry_by_path/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (badgename != null) localVarPathParams.Add("badgename", this.Configuration.ApiClient.ParameterToString(badgename)); // path parameter
            if (path != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "path", path)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForBadgeByPathPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in a badged release Gets a single entry for a given badged release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Entry</returns>
        public Entry GetEntryForBadgePublic (string bucketid, string badgename, string entryid)
        {
             ApiResponse<Entry> localVarResponse = GetEntryForBadgePublicWithHttpInfo(bucketid, badgename, entryid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get entry in a badged release Gets a single entry for a given badged release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Entry</returns>
        public ApiResponse< Entry > GetEntryForBadgePublicWithHttpInfo (string bucketid, string badgename, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForBadgePublic");
            // verify the required parameter 'badgename' is set
            if (badgename == null)
                throw new ApiException(400, "Missing required parameter 'badgename' when calling EntriesApi->GetEntryForBadgePublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryForBadgePublic");

            var localVarPath = "/buckets/{bucketid}/release_by_badge/{badgename}/entries/{entryid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (badgename != null) localVarPathParams.Add("badgename", this.Configuration.ApiClient.ParameterToString(badgename)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForBadgePublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in a badged release Gets a single entry for a given badged release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of Entry</returns>
        public async System.Threading.Tasks.Task<Entry> GetEntryForBadgePublicAsync (string bucketid, string badgename, string entryid)
        {
             ApiResponse<Entry> localVarResponse = await GetEntryForBadgePublicAsyncWithHttpInfo(bucketid, badgename, entryid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get entry in a badged release Gets a single entry for a given badged release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="badgename">Badge Name</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForBadgePublicAsyncWithHttpInfo (string bucketid, string badgename, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForBadgePublic");
            // verify the required parameter 'badgename' is set
            if (badgename == null)
                throw new ApiException(400, "Missing required parameter 'badgename' when calling EntriesApi->GetEntryForBadgePublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryForBadgePublic");

            var localVarPath = "/buckets/{bucketid}/release_by_badge/{badgename}/entries/{entryid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (badgename != null) localVarPathParams.Add("badgename", this.Configuration.ApiClient.ParameterToString(badgename)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForBadgePublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in release by path Gets a single entry for a given release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>Entry</returns>
        public Entry GetEntryForReleaseByPathPublic (string bucketid, string releaseid, string path)
        {
             ApiResponse<Entry> localVarResponse = GetEntryForReleaseByPathPublicWithHttpInfo(bucketid, releaseid, path);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get entry in release by path Gets a single entry for a given release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>ApiResponse of Entry</returns>
        public ApiResponse< Entry > GetEntryForReleaseByPathPublicWithHttpInfo (string bucketid, string releaseid, string path)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForReleaseByPathPublic");
            // verify the required parameter 'releaseid' is set
            if (releaseid == null)
                throw new ApiException(400, "Missing required parameter 'releaseid' when calling EntriesApi->GetEntryForReleaseByPathPublic");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling EntriesApi->GetEntryForReleaseByPathPublic");

            var localVarPath = "/buckets/{bucketid}/releases/{releaseid}/entry_by_path/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (releaseid != null) localVarPathParams.Add("releaseid", this.Configuration.ApiClient.ParameterToString(releaseid)); // path parameter
            if (path != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "path", path)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForReleaseByPathPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in release by path Gets a single entry for a given release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>Task of Entry</returns>
        public async System.Threading.Tasks.Task<Entry> GetEntryForReleaseByPathPublicAsync (string bucketid, string releaseid, string path)
        {
             ApiResponse<Entry> localVarResponse = await GetEntryForReleaseByPathPublicAsyncWithHttpInfo(bucketid, releaseid, path);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get entry in release by path Gets a single entry for a given release by path.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="path">Path</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForReleaseByPathPublicAsyncWithHttpInfo (string bucketid, string releaseid, string path)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForReleaseByPathPublic");
            // verify the required parameter 'releaseid' is set
            if (releaseid == null)
                throw new ApiException(400, "Missing required parameter 'releaseid' when calling EntriesApi->GetEntryForReleaseByPathPublic");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling EntriesApi->GetEntryForReleaseByPathPublic");

            var localVarPath = "/buckets/{bucketid}/releases/{releaseid}/entry_by_path/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (releaseid != null) localVarPathParams.Add("releaseid", this.Configuration.ApiClient.ParameterToString(releaseid)); // path parameter
            if (path != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "path", path)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForReleaseByPathPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in release Gets a single entry for a given release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Entry</returns>
        public Entry GetEntryForReleasePublic (string bucketid, string releaseid, string entryid)
        {
             ApiResponse<Entry> localVarResponse = GetEntryForReleasePublicWithHttpInfo(bucketid, releaseid, entryid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get entry in release Gets a single entry for a given release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Entry</returns>
        public ApiResponse< Entry > GetEntryForReleasePublicWithHttpInfo (string bucketid, string releaseid, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForReleasePublic");
            // verify the required parameter 'releaseid' is set
            if (releaseid == null)
                throw new ApiException(400, "Missing required parameter 'releaseid' when calling EntriesApi->GetEntryForReleasePublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryForReleasePublic");

            var localVarPath = "/buckets/{bucketid}/releases/{releaseid}/entries/{entryid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (releaseid != null) localVarPathParams.Add("releaseid", this.Configuration.ApiClient.ParameterToString(releaseid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForReleasePublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry in release Gets a single entry for a given release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of Entry</returns>
        public async System.Threading.Tasks.Task<Entry> GetEntryForReleasePublicAsync (string bucketid, string releaseid, string entryid)
        {
             ApiResponse<Entry> localVarResponse = await GetEntryForReleasePublicAsyncWithHttpInfo(bucketid, releaseid, entryid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get entry in release Gets a single entry for a given release.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="releaseid">Release ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryForReleasePublicAsyncWithHttpInfo (string bucketid, string releaseid, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryForReleasePublic");
            // verify the required parameter 'releaseid' is set
            if (releaseid == null)
                throw new ApiException(400, "Missing required parameter 'releaseid' when calling EntriesApi->GetEntryForReleasePublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryForReleasePublic");

            var localVarPath = "/buckets/{bucketid}/releases/{releaseid}/entries/{entryid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (releaseid != null) localVarPathParams.Add("releaseid", this.Configuration.ApiClient.ParameterToString(releaseid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryForReleasePublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry by id Gets a single entry by id for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Entry</returns>
        public Entry GetEntryPublic (string bucketid, string entryid)
        {
             ApiResponse<Entry> localVarResponse = GetEntryPublicWithHttpInfo(bucketid, entryid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get entry by id Gets a single entry by id for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>ApiResponse of Entry</returns>
        public ApiResponse< Entry > GetEntryPublicWithHttpInfo (string bucketid, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryPublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryPublic");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry by id Gets a single entry by id for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of Entry</returns>
        public async System.Threading.Tasks.Task<Entry> GetEntryPublicAsync (string bucketid, string entryid)
        {
             ApiResponse<Entry> localVarResponse = await GetEntryPublicAsyncWithHttpInfo(bucketid, entryid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get entry by id Gets a single entry by id for a given bucket.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryPublicAsyncWithHttpInfo (string bucketid, string entryid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryPublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryPublic");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry version Gets a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Entry</returns>
        public Entry GetEntryVersionPublic (string bucketid, string entryid, string versionid)
        {
             ApiResponse<Entry> localVarResponse = GetEntryVersionPublicWithHttpInfo(bucketid, entryid, versionid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get entry version Gets a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>ApiResponse of Entry</returns>
        public ApiResponse< Entry > GetEntryVersionPublicWithHttpInfo (string bucketid, string entryid, string versionid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryVersionPublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryVersionPublic");
            // verify the required parameter 'versionid' is set
            if (versionid == null)
                throw new ApiException(400, "Missing required parameter 'versionid' when calling EntriesApi->GetEntryVersionPublic");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/versions/{versionid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarPathParams.Add("versionid", this.Configuration.ApiClient.ParameterToString(versionid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryVersionPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

        /// <summary>
        /// Get entry version Gets a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of Entry</returns>
        public async System.Threading.Tasks.Task<Entry> GetEntryVersionPublicAsync (string bucketid, string entryid, string versionid)
        {
             ApiResponse<Entry> localVarResponse = await GetEntryVersionPublicAsyncWithHttpInfo(bucketid, entryid, versionid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get entry version Gets a specific version of an entry.
        /// </summary>
        /// <exception cref="CloudContentDeliveryClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bucketid">Bucket ID</param>
        /// <param name="entryid">Entry ID</param>
        /// <param name="versionid">Version ID</param>
        /// <returns>Task of ApiResponse (Entry)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Entry>> GetEntryVersionPublicAsyncWithHttpInfo (string bucketid, string entryid, string versionid)
        {
            // verify the required parameter 'bucketid' is set
            if (bucketid == null)
                throw new ApiException(400, "Missing required parameter 'bucketid' when calling EntriesApi->GetEntryVersionPublic");
            // verify the required parameter 'entryid' is set
            if (entryid == null)
                throw new ApiException(400, "Missing required parameter 'entryid' when calling EntriesApi->GetEntryVersionPublic");
            // verify the required parameter 'versionid' is set
            if (versionid == null)
                throw new ApiException(400, "Missing required parameter 'versionid' when calling EntriesApi->GetEntryVersionPublic");

            var localVarPath = "/buckets/{bucketid}/entries/{entryid}/versions/{versionid}/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bucketid != null) localVarPathParams.Add("bucketid", this.Configuration.ApiClient.ParameterToString(bucketid)); // path parameter
            if (entryid != null) localVarPathParams.Add("entryid", this.Configuration.ApiClient.ParameterToString(entryid)); // path parameter
            if (versionid != null) localVarPathParams.Add("versionid", this.Configuration.ApiClient.ParameterToString(versionid)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetEntryVersionPublic", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Entry>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Entry) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Entry)));
        }

    }
}
