/* 
 * Content Delivery Management API
 *
 * <p>Cloud Content Delivery is a managed cloud service that hosts and delivers content to end users worldwide.</p> <p>You are currently viewing the documentation for the <b>Management API</b>, intended to be used by developers at build time for managing content. Refer to the <a href=\"https://content-api.cloud.unity3d.com/doc_client/\">Content Delivery Client API</a> for documentation about the API intended to be used at runtime by your game client.</p> <h2>Client SDK</h2> <p>The Content Delivery Management API is based on Swagger. The <a href=\"https://swagger.io/tools/swagger-codegen/\">Swagger Code Generator</a> can generate client libraries to integrate with your projects.</p> <p>A <a href=\"https://content-api.cloud.unity3d.com/doc/doc.json\">JSON schema</a> is required to generate a client for this API version.</p> <h2>Authentication</h2> <p>The Content Delivery Management API requires an API key associated with your Unity developer account. To access your API Key, please visit the <a href=\"https://developer.cloud.unity3d.com\">developer dashboard</a>.</p> <p>To authenticate requests, include a Basic Authentication header as a base64-encoded string 'username:password', using your API key as the password (and empty username).</p> <p>For example, an API key value of 'd6d2c026bac44b1ea7ac0332694a830e' would include an Authorization header like:</p> <p><b>Authorization: Basic OmQ2ZDJjMDI2YmFjNDRiMWVhN2FjMDMzMjY5NGE4MzBl</b></p> <h2>Pagination</h2> <p>Paged results take two parameters: the number of results to return per page (?per_page) and the page number based on that per page amount (?page). Page numbering starts with 1 and the default page size is 10.</p> <p>For instance, if there are 40 results and you specify page=2&per_page=10, you will receive records 11-20. Paged results will also return a Content-Range header. In the example above the content range header will look like this:</p> <p><b>Content-Range: items 11-20/40</b></p>
 *
 * OpenAPI spec version: 0.9.112
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using CloudContentDeliveryManagment.Client;
using CloudContentDeliveryManagment.Model;

namespace CloudContentDeliveryManagment.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get user API key
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Userapikey</returns>
        Userapikey GetUserApiKey ();

        /// <summary>
        /// Get user API key
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Userapikey</returns>
        ApiResponse<Userapikey> GetUserApiKeyWithHttpInfo ();
        /// <summary>
        /// Get user info
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s information.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>User</returns>
        User GetUserInfo ();

        /// <summary>
        /// Get user info
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s information.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of User</returns>
        ApiResponse<User> GetUserInfoWithHttpInfo ();
        /// <summary>
        /// Re-generate user API key
        /// </summary>
        /// <remarks>
        /// Re-generate the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>Userapikey</returns>
        Userapikey RegenerateUserApiKey (Userapikey apikey);

        /// <summary>
        /// Re-generate user API key
        /// </summary>
        /// <remarks>
        /// Re-generate the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>ApiResponse of Userapikey</returns>
        ApiResponse<Userapikey> RegenerateUserApiKeyWithHttpInfo (Userapikey apikey);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get user API key
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Userapikey</returns>
        System.Threading.Tasks.Task<Userapikey> GetUserApiKeyAsync ();

        /// <summary>
        /// Get user API key
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Userapikey)</returns>
        System.Threading.Tasks.Task<ApiResponse<Userapikey>> GetUserApiKeyAsyncWithHttpInfo ();
        /// <summary>
        /// Get user info
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s information.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of User</returns>
        System.Threading.Tasks.Task<User> GetUserInfoAsync ();

        /// <summary>
        /// Get user info
        /// </summary>
        /// <remarks>
        /// Gets the current user&#39;s information.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (User)</returns>
        System.Threading.Tasks.Task<ApiResponse<User>> GetUserInfoAsyncWithHttpInfo ();
        /// <summary>
        /// Re-generate user API key
        /// </summary>
        /// <remarks>
        /// Re-generate the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>Task of Userapikey</returns>
        System.Threading.Tasks.Task<Userapikey> RegenerateUserApiKeyAsync (Userapikey apikey);

        /// <summary>
        /// Re-generate user API key
        /// </summary>
        /// <remarks>
        /// Re-generate the current user&#39;s API key.
        /// </remarks>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>Task of ApiResponse (Userapikey)</returns>
        System.Threading.Tasks.Task<ApiResponse<Userapikey>> RegenerateUserApiKeyAsyncWithHttpInfo (Userapikey apikey);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UsersApi : IUsersApi
    {
        private CloudContentDeliveryManagment.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsersApi(String basePath)
        {
            this.Configuration = new CloudContentDeliveryManagment.Client.Configuration { BasePath = basePath };

            ExceptionFactory = CloudContentDeliveryManagment.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UsersApi(CloudContentDeliveryManagment.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = CloudContentDeliveryManagment.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = CloudContentDeliveryManagment.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CloudContentDeliveryManagment.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CloudContentDeliveryManagment.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get user API key Gets the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Userapikey</returns>
        public Userapikey GetUserApiKey ()
        {
             ApiResponse<Userapikey> localVarResponse = GetUserApiKeyWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get user API key Gets the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Userapikey</returns>
        public ApiResponse< Userapikey > GetUserApiKeyWithHttpInfo ()
        {

            var localVarPath = "/users/me/apikey/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserApiKey", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Userapikey>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Userapikey) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Userapikey)));
        }

        /// <summary>
        /// Get user API key Gets the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of Userapikey</returns>
        public async System.Threading.Tasks.Task<Userapikey> GetUserApiKeyAsync ()
        {
             ApiResponse<Userapikey> localVarResponse = await GetUserApiKeyAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get user API key Gets the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (Userapikey)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Userapikey>> GetUserApiKeyAsyncWithHttpInfo ()
        {

            var localVarPath = "/users/me/apikey/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserApiKey", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Userapikey>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Userapikey) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Userapikey)));
        }

        /// <summary>
        /// Get user info Gets the current user&#39;s information.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>User</returns>
        public User GetUserInfo ()
        {
             ApiResponse<User> localVarResponse = GetUserInfoWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get user info Gets the current user&#39;s information.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of User</returns>
        public ApiResponse< User > GetUserInfoWithHttpInfo ()
        {

            var localVarPath = "/users/me/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

        /// <summary>
        /// Get user info Gets the current user&#39;s information.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of User</returns>
        public async System.Threading.Tasks.Task<User> GetUserInfoAsync ()
        {
             ApiResponse<User> localVarResponse = await GetUserInfoAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get user info Gets the current user&#39;s information.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (User)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<User>> GetUserInfoAsyncWithHttpInfo ()
        {

            var localVarPath = "/users/me/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetUserInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<User>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (User) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(User)));
        }

        /// <summary>
        /// Re-generate user API key Re-generate the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>Userapikey</returns>
        public Userapikey RegenerateUserApiKey (Userapikey apikey)
        {
             ApiResponse<Userapikey> localVarResponse = RegenerateUserApiKeyWithHttpInfo(apikey);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Re-generate user API key Re-generate the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>ApiResponse of Userapikey</returns>
        public ApiResponse< Userapikey > RegenerateUserApiKeyWithHttpInfo (Userapikey apikey)
        {
            // verify the required parameter 'apikey' is set
            if (apikey == null)
                throw new ApiException(400, "Missing required parameter 'apikey' when calling UsersApi->RegenerateUserApiKey");

            var localVarPath = "/users/me/apikey/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apikey != null && apikey.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(apikey); // http body (model) parameter
            }
            else
            {
                localVarPostBody = apikey; // byte array
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegenerateUserApiKey", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Userapikey>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Userapikey) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Userapikey)));
        }

        /// <summary>
        /// Re-generate user API key Re-generate the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>Task of Userapikey</returns>
        public async System.Threading.Tasks.Task<Userapikey> RegenerateUserApiKeyAsync (Userapikey apikey)
        {
             ApiResponse<Userapikey> localVarResponse = await RegenerateUserApiKeyAsyncWithHttpInfo(apikey);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Re-generate user API key Re-generate the current user&#39;s API key.
        /// </summary>
        /// <exception cref="CloudContentDeliveryManagment.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey">ApiKey</param>
        /// <returns>Task of ApiResponse (Userapikey)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Userapikey>> RegenerateUserApiKeyAsyncWithHttpInfo (Userapikey apikey)
        {
            // verify the required parameter 'apikey' is set
            if (apikey == null)
                throw new ApiException(400, "Missing required parameter 'apikey' when calling UsersApi->RegenerateUserApiKey");

            var localVarPath = "/users/me/apikey/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apikey != null && apikey.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(apikey); // http body (model) parameter
            }
            else
            {
                localVarPostBody = apikey; // byte array
            }

            // authentication (ApiKeyAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegenerateUserApiKey", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Userapikey>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Userapikey) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Userapikey)));
        }

    }
}
